### ISSUE TITLE
number 0 or boolean false do not validate

### ISSUE THREAD

**Issue by JADurham909** [eivindfjeldstad/validate#23] opened 2015-08-14 15:55 UTC
Numbers with value 0 or booleans set to false will not validate.  I suspect its failing a truthy test in property.validate.

passwordBad: {
            type: 'boolean',
            required: false
        }

validate({
        domain: domainWithPassword,
        user: 'justin',
        password: password,
        passwordBad: false
})

or

passwordBad: {
            type: 'number',
            required: false
        }

validate({
        domain: domainWithPassword,
        user: 'justin',
        password: password,
        passwordBad: 0
})

**Comment by CocaCola183** [comment] 2015-08-20 07:20
@JADurham909 I got the same problem

**Comment by CocaCola183** [comment] 2015-08-20 07:34
property.js 

line 153
```
var valid = fn[0].call(ctx, value);
```

line 168~172

```
function required () {
  return function (value) {
    return !!value;
  }
}
```

in this way, if I pass 0(number) or false(bollean), it will return !!0 or !!false

**Comment by eivindfjeldstad** [comment] 2015-08-20 08:05
hm, yeah thats probably not ideal. maybe something like this instead:
```js
function required () {
  return function (value) {
    return value == null;
  }
}
```

**Comment by eivindfjeldstad** [comment] 2015-08-20 08:09
The problem is that most people pass in objects constructed from query strings or request bodies. I would expect an empty string to be considered invalid. I'm not sure about 0 though.

**Comment by throoze** [comment] 2017-05-02 21:04
Hi! I still get the same problem. boolean false does not validate. Will you address this issue in the short term?

**Comment by rlingineni** [comment] 2017-10-01 04:07
+1 Same problem here. `boolean:false` fails

**Comment by mmitrukaa** [comment] 2018-02-26 17:08
+1 Same problem , need a fix

**Comment by eivindfjeldstad** [comment] 2018-03-12 10:09
There's a new branch out for version 4. I'm open to changing the way `.required` works. I agree that `false` should not be considered invalid

**Comment by eivindfjeldstad** [comment] 2018-03-17 11:40
fixed in 4.0.0

**Closed by eivindfjeldstad** 2018-03-17 11:40 UTC
